cryptogarageinc/quickfix-go

- Makefile
- _test/ReflectorClient.rb
- chore: build on windows
- test: guard eof check. (ruby's bug)
> chore: update

- acceptor.go
- initiator.go
acceptorとinitiatorにAPI追加。
なおテストはタグ打ち後にexampleを改造して実施。
> feat: add acceptor API

- acceptor.go
- session.go
- fix: add allSessions (for dynamic session)
- fix: add mutex lock (from quickfixgo issue 436)
> fix: get sessionID on dynamic session

- acceptor.go
- initiator.go
- registry.go
- settings.go
fix: add fillHeaderBySessionID for SendToLiveSessions.
> fix: SendToLiveSessions

- acceptor.go
> feat: add IsLiveSession, etc.

- initiator.go
- session.go
> (WIP) feat: add wait api

- errors.go
- errors_test.go
feat: add other error to BusinessRejectReason
> feat: add other error to BusinessRejectReason (#25)

- config/configuration.go
- config/doc.go
- sqlstore.go
- sqlstore_test.go
- feat: merge from alpaca 20210717
- Add max idle and open connections settings (a00f69f)
> feat: merge from alpaca 20210717

- filestore.go
- mongostore.go
- sqlstore.go
- fix: message store with global config (for dynamic session)
> fix: message store with global config (for dynamic session)

- config/configuration.go
- config/doc.go
- internal/session_settings.go
- logon_state_test.go
- message_build.go
- session.go
- session_factory.go
- session_factory_test.go
- validation.go
- validation_test.go
- merge form quickfixgo
- 454: Expose Validator as a publicly accessible interface
- 455: add configuration HeartBtIntOverride
> feat: merge quickfixgo 20210825

- validation.go
- validation_test.go
- fix: modify group validate
- currently, need first group data.
> fix: modify group validate

- datadictionary/datadictionary.go
- repeating_group.go
- repeating_group_test.go
- validation.go
- fix: repeating group delimiter
- refactor: validate check
> fix: repeating group

- validation.go
- fix: add required check from skip fields
- v1.0.10 ～ v1.0.11 の不備修正
> fix: add required check from skip fields

- .github/workflows/ci.yaml
- _test/echo_server.go
- support go 1.18
- fix: signal.Notify
> test: support go 1.18

- field_map.go
- field_map_test.go
- tls.go
- tls_test.go
- quickfixgo
- Make use of SocketCAFile config
- alpacahq
- delete tag from fix
> feat: update from upstream

- acceptor.go
- add receive error log on acceptor
- except where msgBytes have already been recorded
> feat: add receive error log on acceptor

- acceptor.go
- connection.go
- custom_log.go
- file_log.go
- in_session.go
- initiator.go
- latent_state.go
- log.go
- logon_state.go
- not_session_time.go
- null_log.go
- pending_timeout.go
- screen_log.go
- session.go
- session_state.go
- add log interface
- change calling log function
> feat: add log interface

- go.mod
- go.sum
> feat: update testify

- .github/workflows/ci.yaml
- .golangci.yml
- _test/echo_server.go
- filestore.go
- sqlstore_test.go
- tls.go
- fix: lint for ioutil
- feat: golangci-lint verup
> fix: lint for ioutil

- .github/workflows/ci.yaml
- .github/workflows/codeql-analysis.yml
- docker-compose.yaml
- test: use mongo 5
- mongo 6 has failed test.
- test: update actions
- test: add go cache
> fix: test update

- session.go
- fix: session.stop
- from quickfixgo/quickfix pr 531
> fix: session.stop from quickfixgo/quickfix pr 531

- .editorconfig
- .github/dependabot.yml
- .github/workflows/ci.yaml
- .github/workflows/codeql-analysis.yml
- .golangci.yml
- .yamlfmt
- Makefile
- feat: update tools
- style: format yaml
- feat: update cache logic on CI
> feat: update tools 20230822

- .github/workflows/ci.yaml
- .github/workflows/codeql-analysis.yml
- go.mod
- feat: support go 1.21
- feat: upgrade github actions uses
> feat: upgrade 20240215
